name: Build package

on:
  workflow_dispatch:
    inputs:
      package:
        description: The name of the package to build.
        required: true

jobs:
  build_package:
    name: Build package ${{github.event.inputs.package}}
    runs-on: ubuntu-latest
    steps:
      - name: Check out PKGBUILD's
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Start docker container
        id: container
        run: docker run --name build -v $(pwd):/build -d --rm -it archlinux:base-devel cat && sleep 5

      - name: Setting up container
        run: |
          docker exec -i build pacman -Syu --noconfirm git namcap sudo \
          && docker exec -i build bash -c "echo ALL ALL=NOPASSWD: /usr/bin/pacman > /etc/sudoers.d/pacman"

      - name: Building package
        run: |
          docker exec -i -u nobody -w /build/${{github.event.inputs.package}} build makepkg -s --noconfirm -f

      - name: Stopping container
        if: always()
        run: |
          docker stop build || exit 0

      - name: Check out packages
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          ref: packages
          path: packages

      - name: Copying packages
        run: |
          (cp ${{github.event.inputs.package}}/*-x86_64.pkg.tar.zst packages/x86_64 || 1) \
          && (cp ${{github.event.inputs.package}}/-any.pkg.tar.zst packages/x86_64 || 1) \

      - name: Updating packages database
        run: |
          cd packages/x86_64 \
          && repo-add ribugent.db.tar.xz *.pkg.tar.zst

      - name: "Committing packages"
        run: |
          cd packages \
          && git add . \
          && git commit -m "Update packages" \
          && git push origin packages
